export const movieDatabase = [
    // ACTION 
    { title: "Kung Fu Hustle", genre: "action", mood: "lighthearted", duration: "short", poster: "assets/p/action1.jpg", desc: "A bumbling thief tries to scam a neighborhood, sparking a war between gangs." },
    { title: "Turbo", genre: "action", mood: "lighthearted", duration: "short", poster: "assets/p/action2.jpg", desc: "A snail with the dream of winning the Indy 500." },
    { title: "The Nice Guys", genre: "action", mood: "lighthearted", duration: "medium", poster: "assets/p/action3.jpg", desc: "A mismatched pair of private eyes investigate a missing girl." },
    { title: "Free Guy", genre: "action", mood: "lighthearted", duration: "medium", poster: "assets/p/action4.jpg", desc: "A bank teller discovers he is a background character in a video game." },
    { title: "The Blues Brothers", genre: "action", mood: "lighthearted", duration: "long", poster: "assets/p/action5.jpg", desc: "Two brothers go on a mission from God to save an orphanage." },
    { title: "Indiana Jones: Dial of Destiny", genre: "action", mood: "lighthearted", duration: "long", poster: "assets/p/action6.jpg", desc: "The legendary archaeologist races against time to retrieve a legendary dial." },

    { title: "Inception", genre: "action", mood: "thought-provoking", duration: "long", poster: "assets/p/action7.jpg", desc: "A thief who steals corporate secrets through dream-sharing technology." },
    { title: "Tenet", genre: "action", mood: "thought-provoking", duration: "long", poster: "assets/p/action8.jpg", desc: "A secret agent embarks on a mission that unfolds beyond real time." },
    { title: "The Matrix", genre: "action", mood: "thought-provoking", duration: "medium", poster: "assets/p/action9.jpg", desc: "A computer hacker learns from mysterious rebels about the true nature of his reality." },
    { title: "Source Code", genre: "action", mood: "thought-provoking", duration: "medium", poster: "assets/p/action10.jpg", desc: "A soldier wakes up in someone else's body on a commuter train." },
    { title: "Dredd", genre: "action", mood: "thought-provoking", duration: "short", poster: "assets/p/action11.jpg", desc: "In a violent futuristic city, the police have the authority to act as judge, jury and executioner." },
    { title: "District 9", genre: "action", mood: "thought-provoking", duration: "short", poster: "assets/p/action12.jpg", desc: "Violence ensues after an extraterrestrial race is forced to live in slum-like conditions." },

    { title: "Gladiator", genre: "action", mood: "emotional", duration: "long", poster: "assets/p/action13.jpg", desc: "A former Roman General sets out to exact vengeance against the corrupt emperor." },
    { title: "Braveheart", genre: "action", mood: "emotional", duration: "long", poster: "assets/p/action14.jpg", desc: "William Wallace leads the Scots in a war against the King of England." },
    { title: "Logan", genre: "action", mood: "emotional", duration: "medium", poster: "assets/p/action15.jpg", desc: "In the near future, a weary Logan cares for an ailing Professor X." },
    { title: "The Last Samurai", genre: "action", mood: "emotional", duration: "medium", poster: "assets/p/action16.jpg", desc: "An American military advisor embraces the Samurai culture he was hired to destroy." },
    { title: "Taken", genre: "action", mood: "emotional", duration: "short", poster: "assets/p/action17.jpg", desc: "A retired CIA agent travels across Europe to save his estranged daughter." },
    { title: "John Wick", genre: "action", mood: "emotional", duration: "short", poster: "assets/p/action18.jpg", desc: "An ex-hitman comes out of retirement to track down the men that killed his dog." },

    { title: "Rush Hour", genre: "action", mood: "funny", duration: "short", poster: "assets/p/action19.jpg", desc: "A loyal Hong Kong inspector teams up with a reckless L.A.P.D. detective." },
    { title: "Deadpool", genre: "action", mood: "funny", duration: "short", poster: "assets/p/action20.jpg", desc: "A wisecracking mercenary is experimented on and becomes immortal." },
    { title: "21 Jump Street", genre: "action", mood: "funny", duration: "medium", poster: "assets/p/action21.jpg", desc: "Two underachieving cops are sent back to a local high school to blend in." },
    { title: "Bad Boys for Life", genre: "action", mood: "funny", duration: "medium", poster: "assets/p/action22.jpg", desc: "Miami detectives Mike Lowrey and Marcus Burnett must face off against a mother-and-son pair of drug lords." },
    { title: "Tropic Thunder", genre: "action", mood: "funny", duration: "long", poster: "assets/p/action23.jpg", desc: "A group of actors shooting a war movie are forced to become the soldiers they are portraying." },
    { title: "Hot Fuzz", genre: "action", mood: "funny", duration: "long", poster: "assets/p/action24.jpg", desc: "A skilled London police officer is transferred to a small town with a dark secret." },

    { title: "Lone Survivor", genre: "action", mood: "sad", duration: "medium", poster: "assets/p/action25.jpg", desc: "Marcus Luttrell and his team set out on a mission to capture or kill notorious Taliban leader." },
    { title: "Fury", genre: "action", mood: "sad", duration: "medium", poster: "assets/p/action26.jpg", desc: "A grizzled tank commander makes tough decisions as he and his crew fight across Germany." },
    { title: "Extraction", genre: "action", mood: "sad", duration: "short", poster: "assets/p/action27.jpg", desc: "A black-market mercenary is hired to rescue the kidnapped son of an imprisoned international crime lord." },
    { title: "The Revenant", genre: "action", mood: "sad", duration: "long", poster: "assets/p/action28.jpg", desc: "A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear." },
    { title: "Black Hawk Down", genre: "action", mood: "sad", duration: "long", poster: "assets/p/action29.jpg", desc: "The story of 160 elite U.S. soldiers who dropped into Mogadishu in 1993." },
    { title: "Crouching Tiger, Hidden Dragon", genre: "action", mood: "sad", duration: "medium", poster: "assets/p/action30.jpg", desc: "A young Chinese warrior steals a sword from a famed swordsman and then escapes into a world of romantic adventure." },

    
    // COMEDY 
    { title: "Paddington 2", genre: "comedy", mood: "lighthearted", duration: "short", poster: "assets/p/c1.jpg", desc: "Paddington, now settled with the Brown family, picks up a series of odd jobs to buy the perfect present." },
    { title: "The Emperor's New Groove", genre: "comedy", mood: "lighthearted", duration: "short", poster: "assets/p/c2.jpg", desc: "Emperor Kuzco is turned into a llama by his ex-administrator and must regain his throne with the help of a gentle peasant." },
    { title: "Ferris Bueller's Day Off", genre: "comedy", mood: "lighthearted", duration: "medium", poster: "assets/p/c3.jpg", desc: "A high school wise guy is determined to have a day off from school, despite what the principal thinks." },
    { title: "Mrs. Doubtfire", genre: "comedy", mood: "lighthearted", duration: "medium", poster: "assets/p/c4.jpg", desc: "After a bitter divorce, an actor disguises himself as a female housekeeper to spend time with his children." },
    { title: "Forrest Gump", genre: "comedy", mood: "lighthearted", duration: "long", poster: "assets/p/c5.jpg", desc: "The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold from the perspective of an Alabama man." },
    { title: "The Princess Bride", genre: "comedy", mood: "lighthearted", duration: "long", poster: "assets/p/c6.jpg", desc: "A fair maiden's journey to find her true love, filled with fencing, fighting, giants, and miracles." },

    { title: "The Truman Show", genre: "comedy", mood: "thought-provoking", duration: "medium", poster: "assets/p/c7.jpg", desc: "An insurance salesman discovers his whole life is actually a reality TV show." },
    { title: "Groundhog Day", genre: "comedy", mood: "thought-provoking", duration: "medium", poster: "assets/p/c8.jpg", desc: "A narcissistic TV weatherman finds himself reliving the same day over and over again." },
    { title: "The Big Short", genre: "comedy", mood: "thought-provoking", duration: "long", poster: "assets/p/c9.jpg", desc: "In 2006-2007, a group of investors bet against the US mortgage market and discover how corrupt the market is." },
    { title: "Dr. Strangelove", genre: "comedy", mood: "thought-provoking", duration: "long", poster: "assets/p/c10.jpg", desc: "An insane American general orders a bombing attack on the Soviet Union, triggering a path to nuclear apocalypse." },
    { title: "Being John Malkovich", genre: "comedy", mood: "thought-provoking", duration: "short", poster: "assets/p/c11.jpg", desc: "A puppeteer discovers a portal that leads literally into the head of movie star John Malkovich." },
    { title: "The Lobster", genre: "comedy", mood: "thought-provoking", duration: "short", poster: "assets/p/c12.jpg", desc: "In a dystopian near future, single people are arrested and transferred to a hotel where they must find a partner in 45 days." },
    
    { title: "Little Miss Sunshine", genre: "comedy", mood: "emotional", duration: "medium", poster: "assets/p/c13.jpg", desc: "A family determines to get their young daughter into the finals of a beauty pageant via a cross-country journey in their VW bus." },
    { title: "The Intouchables", genre: "comedy", mood: "emotional", duration: "medium", poster: "assets/p/c14.jpg", desc: "After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver." },
    { title: "The Green Book", genre: "comedy", mood: "emotional", duration: "long", poster: "assets/p/c15.jpg", desc: "A working-class Italian-American bouncer becomes the driver of an African-American classical pianist on a tour through the 1960s American South." },
    { title: "About Time", genre: "comedy", mood: "emotional", duration: "long", poster: "assets/p/c16.jpg", desc: "At the age of 21, Tim discovers he can travel in time and change what happens and has happened in his own life." },
    { title: "Up", genre: "comedy", mood: "emotional", duration: "short", poster: "assets/p/c17.jpg", desc: "78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway." },
    { title: "50/50", genre: "comedy", mood: "emotional", duration: "short", poster: "assets/p/c18.jpg", desc: "Inspired by a true story, a 27-year-old guy learns of his cancer diagnosis and his subsequent struggle to beat the disease." },
   
    { title: "Superbad", genre: "comedy", mood: "funny", duration: "short", poster: "assets/p/c19.jpg", desc: "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry." },
    { title: "Dumb and Dumber", genre: "comedy", mood: "funny", duration: "short", poster: "assets/p/c20.jpg", desc: "After a gentlewoman leaves a briefcase in the terminal, two well-meaning but incredibly stupid friends drive across the country to return it." },
    { title: "The Hangover", genre: "comedy", mood: "funny", duration: "medium", poster: "assets/p/c21.jpg", desc: "Three buddies wake up from a bachelor party in Las Vegas with no memory of the previous night and the bachelor missing." },
    { title: "Step Brothers", genre: "comedy", mood: "funny", duration: "medium", poster: "assets/p/c22.jpg", desc: "Two middle-aged losers living at home are forced to become roommates when their parents marry." },
    { title: "Bridesmaids", genre: "comedy", mood: "funny", duration: "long", poster: "assets/p/c23.jpg", desc: "Competition between the maid of honor and a bridesmaid, over who is the bride's best friend, threatens to upend the wedding." },
    { title: "Borat", genre: "comedy", mood: "funny", duration: "long", poster: "assets/p/c24.jpg", desc: "Kazakh TV talking head Borat is dispatched to the United States to report on the greatest country in the world." },
    
    { title: "The Royal Tenenbaums", genre: "comedy", mood: "sad", duration: "medium", poster: "assets/p/c25.jpg", desc: "The eccentric members of a dysfunctional family reluctantly gather under the same roof for various reasons." },
    { title: "500 Days of Summer", genre: "comedy", mood: "sad", duration: "medium", poster: "assets/p/c26.jpg", desc: "An offbeat romantic comedy about a woman who doesn't believe true love exists, and the young man who falls for her." },
    { title: "Life is Beautiful", genre: "comedy", mood: "sad", duration: "long", poster: "assets/p/c27.jpg", desc: "A Jewish librarian and his son become victims of the Holocaust. He uses a perfect mixture of will, humor, and imagination to protect his son." },
    { title: "JoJo Rabbit", genre: "comedy", mood: "sad", duration: "long", poster: "assets/p/c28.jpg", desc: "A young boy in Hitler's army finds out his mother is hiding a Jewish girl in their home." },
    { title: "The Worst Person in the World", genre: "comedy", mood: "sad", duration: "short", poster: "assets/p/c29.jpg", desc: "The chronicles of four years in the life of Julie, a young woman who navigates the troubled waters of her love life and struggles to find her career path." },
    { title: "Manchester by the Sea", genre: "comedy", mood: "sad", duration: "short", poster: "assets/p/c30.jpg", desc: "A depressed uncle is asked to take care of his teenage nephew after the boy's father dies." },

    // HORROR
    { title: "Shaun of the Dead", genre: "horror", mood: "lighthearted", duration: "medium", poster: "assets/p/h1.jpg", desc: "A man's uneventful life is disrupted by the zombie apocalypse, forcing him to save his friends and family." },
    { title: "Gremlins", genre: "horror", mood: "lighthearted", duration: "medium", poster: "assets/p/h2.jpg", desc: "A boy inadvertently breaks three important rules concerning his new pet and unleashes a horde of malevolently mischievous monsters." },
    { title: "Killer Klowns from Outer Space", genre: "horror", mood: "lighthearted", duration: "short", poster: "assets/p/h3.jpg", desc: "Aliens who look like clowns come from another galaxy and harvest townspeople in cocoons of cotton candy." },
    { title: "Critters", genre: "horror", mood: "lighthearted", duration: "short", poster: "assets/p/h4.jpg", desc: "A group of small, furry aliens with many teeth escape from a transport ship and land on Earth to feed." },
    { title: "Army of Darkness", genre: "horror", mood: "lighthearted", duration: "long", poster: "assets/p/h5.jpg", desc: "A man is accidentally transported to 1300 A.D., where he must battle an army of the dead and retrieve the Necronomicon." },
    { title: "Ghostbusters", genre: "horror", mood: "lighthearted", duration: "long", poster: "assets/p/h6.jpg", desc: "Three parapsychologists set up a ghost-removal service in New York City and face an ancient god." },

    { title: "The Shining", genre: "horror", mood: "thought-provoking", duration: "long", poster: "assets/p/h7.jpg", desc: "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence." },
    { title: "Midsommar", genre: "horror", mood: "thought-provoking", duration: "long", poster: "assets/p/h8.jpg", desc: "A couple travels to Scandinavia to visit a rural hometown's fabled midsummer festival that turns into a pagan nightmare." },
    { title: "Get Out", genre: "horror", mood: "thought-provoking", duration: "medium", poster: "assets/p/h9.jpg", desc: "A young African-American visits his white girlfriend's parents for the weekend and discovers a disturbing secret." },
    { title: "It Follows", genre: "horror", mood: "thought-provoking", duration: "medium", poster: "assets/p/h10.jpg", desc: "A young woman is followed by an unknown supernatural force after a sexual encounter, passing the curse to others." },
    { title: "The Lighthouse", genre: "horror", mood: "thought-provoking", duration: "short", poster: "assets/p/h11.jpg", desc: "Two lighthouse keepers try to maintain their sanity while living on a remote and mysterious New England island." },
    { title: "The VVitch", genre: "horror", mood: "thought-provoking", duration: "short", poster: "assets/p/h12.jpg", desc: "A 1630s New England family is torn apart by the forces of witchcraft, black magic, and possession." },

    { title: "A Quiet Place", genre: "horror", mood: "emotional", duration: "short", poster: "assets/p/h13.jpg", desc: "A family must live life in silence while hiding from creatures that hunt by sound, testing their survival and bond." },
    { title: "The Others", genre: "horror", mood: "emotional", duration: "short", poster: "assets/p/h14.jpg", desc: "A woman who lives in a darkened old family house believes her home is haunted while waiting for her husband's return." },
    { title: "The Babadook", genre: "horror", mood: "emotional", duration: "medium", poster: "assets/p/h15.jpg", desc: "A widowed mother and her son fall into a deep well of paranoia when a disturbing children's book manifests in their home." },
    { title: "The Orphanage", genre: "horror", mood: "emotional", duration: "medium", poster: "assets/p/h16.jpg", desc: "A woman brings her family back to her childhood home, where her son begins communicating with invisible friends." },
    { title: "The Conjuring", genre: "horror", mood: "emotional", duration: "long", poster: "assets/p/h17.jpg", desc: "Paranormal investigators work to help a family terrorized by a dark presence in their farmhouse, based on a true story." },
    { title: "Doctor Sleep", genre: "horror", mood: "emotional", duration: "long", poster: "assets/p/h18.jpg", desc: "Years after the events of The Shining, Dan Torrance must protect a young girl with similar powers from a cult." },

    { title: "Tucker & Dale vs. Evil", genre: "horror", mood: "funny", duration: "short", poster: "assets/p/h19.jpg", desc: "Affable hillbillies are mistaken for chainsaw-wielding killers by a group of preppy college students." },
    { title: "Evil Dead II", genre: "horror", mood: "funny", duration: "short", poster: "assets/p/h20.jpg", desc: "The lone survivor of an onslaught of flesh-possessing spirits holes up in a cabin with a group of strangers." },
    { title: "Zombieland", genre: "horror", mood: "funny", duration: "medium", poster: "assets/p/h21.jpg", desc: "A shy student trying to reach his family in Ohio teams up with a gun-toting tough guy in a world overrun by zombies." },
    { title: "Barbarian", genre: "horror", mood: "funny", duration: "medium", poster: "assets/p/h22.jpg", desc: "A woman staying at an Airbnb discovers that the house she has rented is not what it seems, leading to bizarre horror." },
    { title: "Cabin in the Woods", genre: "horror", mood: "funny", duration: "long", poster: "assets/p/h23.jpg", desc: "Five friends go for a break at a remote cabin, where they get more than they bargained for in a subversion of tropes." },
    { title: "Scream", genre: "horror", mood: "funny", duration: "long", poster: "assets/p/h24.jpg", desc: "A year after her mother's murder, a teenage girl is terrorized by a new killer who uses horror films as part of a deadly game." },

    { title: "The Mist", genre: "horror", mood: "sad", duration: "medium", poster: "assets/p/h25.jpg", desc: "A strange mist traps a small town in a grocery store, where they must fight creatures and each other to survive." },
    { title: "Train to Busan", genre: "horror", mood: "sad", duration: "medium", poster: "assets/p/h26.jpg", desc: "While a zombie virus breaks out in South Korea, passengers struggle to survive on the train from Seoul to Busan." },
    { title: "Hostel", genre: "horror", mood: "sad", duration: "short", poster: "assets/p/h27.jpg", desc: "Three backpackers head to a Slovakian city that promises to meet their hedonistic expectations, only to find a dark reality." },
    { title: "The Fly", genre: "horror", mood: "sad", duration: "short", poster: "assets/p/h28.jpg", desc: "A brilliant but eccentric scientist begins to transform into a giant man/fly hybrid after an experiment goes wrong." },
    { title: "The Haunting in Connecticut", genre: "horror", mood: "sad", duration: "long", poster: "assets/p/h29.jpg", desc: "A family moves to a house that used to be a mortuary to be closer to their son's cancer treatment, facing dark spirits." },
    { title: "Hereditary", genre: "horror", mood: "sad", duration: "long", poster: "assets/p/h30.jpg", desc: "A grieving family is haunted by tragic and disturbing occurrences after the death of their secretive grandmother." },

    // SCI-FI
    { title: "Wall-E", genre: "sci-fi", mood: "lighthearted", duration: "short", poster: "assets/p/sf1.jpg", desc: "A waste-collecting robot embarks on a space journey that will decide the fate of mankind." },
    { title: "Short Circuit", genre: "sci-fi", mood: "lighthearted", duration: "short", poster: "assets/p/sf2.jpg", desc: "Number 5 is alive! An experimental military robot gains a personality after a lightning strike." },
    { title: "Back to the Future", genre: "sci-fi", mood: "lighthearted", duration: "medium", poster: "assets/p/sf3.jpg", desc: "A teenager is accidentally sent 30 years into the past in a time-traveling DeLorean." },
    { title: "The Fifth Element", genre: "sci-fi", mood: "lighthearted", duration: "medium", poster: "assets/p/sf4.jpg", desc: "A cab driver becomes the central figure in a search for a legendary cosmic weapon." },
    { title: "Avatar", genre: "sci-fi", mood: "lighthearted", duration: "long", poster: "assets/p/sf5.jpg", desc: "A Marine on a unique mission becomes torn between following orders and protecting a new world." },
    { title: "Star Wars: A New Hope", genre: "sci-fi", mood: "lighthearted", duration: "long", poster: "assets/p/sf6.jpg", desc: "A farm boy joins a galactic rebellion to save a princess and the galaxy from a space station." },

    { title: "Primer", genre: "sci-fi", mood: "thought-provoking", duration: "short", poster: "assets/p/sf7.jpg", desc: "Two engineers accidentally discover a means of time travel with unexpected consequences." },
    { title: "Coherence", genre: "sci-fi", mood: "thought-provoking", duration: "short", poster: "assets/p/sf8.jpg", desc: "Strange things happen at a dinner party when a comet passes overhead, blurring reality." },
    { title: "Ex Machina", genre: "sci-fi", mood: "thought-provoking", duration: "medium", poster: "assets/p/sf9.jpg", desc: "A programmer participates in a ground-breaking experiment in synthetic intelligence." },
    { title: "Blade Runner", genre: "sci-fi", mood: "thought-provoking", duration: "medium", poster: "assets/p/sf10.jpg", desc: "A specialized cop must hunt down four replicants who have returned to Earth illegally." },
    { title: "Interstellar", genre: "sci-fi", mood: "thought-provoking", duration: "long", poster: "assets/p/sf11.jpg", desc: "A team of explorers travel through a wormhole in space to ensure humanity's survival." },
    { title: "Inception", genre: "sci-fi", mood: "thought-provoking", duration: "long", poster: "assets/p/sf12.jpg", desc: "A thief steals corporate secrets through dream-sharing technology and is tasked with inception." },

    { title: "The Iron Giant", genre: "sci-fi", mood: "emotional", duration: "short", poster: "assets/p/sf13.jpg", desc: "A young boy befriends a giant robot from outer space that the government wants to destroy." },
    { title: "Gravity", genre: "sci-fi", mood: "emotional", duration: "short", poster: "assets/p/sf14.jpg", desc: "Two astronauts work together to survive after an accident leaves them stranded in space." },
    { title: "Arrival", genre: "sci-fi", mood: "emotional", duration: "medium", poster: "assets/p/sf15.jpg", desc: "A linguist works with the military to communicate with aliens after spacecraft land around the world." },
    { title: "Her", genre: "sci-fi", mood: "emotional", duration: "medium", poster: "assets/p/sf16.jpg", desc: "A lonely writer develops an unlikely relationship with an operating system designed to meet his needs." },
    { title: "Eternal Sunshine", genre: "sci-fi", mood: "emotional", duration: "long", poster: "assets/p/sf17.jpg", desc: "A couple undergoes a medical procedure to have each other erased from their memories." },
    { title: "Cloud Atlas", genre: "sci-fi", mood: "emotional", duration: "long", poster: "assets/p/sf18.jpg", desc: "An exploration of how the actions of individual lives impact one another through time." },

    { title: "Mars Attacks!", genre: "sci-fi", mood: "funny", duration: "short", poster: "assets/p/sf19.jpg", desc: "Earth is invaded by Martians with unbeatable weapons and a cruel sense of humor." },
    { title: "Hitchhiker's Guide", genre: "sci-fi", mood: "funny", duration: "short", poster: "assets/p/sf20.jpg", desc: "A man is whisked off into space seconds before the Earth is demolished by aliens." },
    { title: "Galaxy Quest", genre: "sci-fi", mood: "funny", duration: "medium", poster: "assets/p/sf21.jpg", desc: "The cast of a space-opera series are recruited by real aliens who believe the show is a documentary." },
    { title: "Men in Black", genre: "sci-fi", mood: "funny", duration: "medium", poster: "assets/p/sf22.jpg", desc: "A police officer joins a secret organization that polices extraterrestrial interactions on Earth." },
    { title: "Guardians of the Galaxy", genre: "sci-fi", mood: "funny", duration: "long", poster: "assets/p/sf23.jpg", desc: "A group of intergalactic criminals must pull together to stop a fanatical warrior." },
    { title: "Ghostbusters", genre: "sci-fi", mood: "funny", duration: "long", poster: "assets/p/sf24.jpg", desc: "Three parapsychologists set up a ghost-removal service and face an ancient god." },

    { title: "Melancholia", genre: "sci-fi", mood: "sad", duration: "short", poster: "assets/p/sf25.jpg", desc: "Two sisters find their relationship challenged as a planet threatens to collide with Earth." },
    { title: "The Quiet Earth", genre: "sci-fi", mood: "sad", duration: "short", poster: "assets/p/sf26.jpg", desc: "A man wakes up to find himself alone in the world and gradually begins to lose his mind." },
    { title: "Never Let Me Go", genre: "sci-fi", mood: "sad", duration: "medium", poster: "assets/p/sf27.jpg", desc: "Friends at a boarding school discover the heartbreaking reality of their existence." },
    { title: "Gattaca", genre: "sci-fi", mood: "sad", duration: "medium", poster: "assets/p/sf28.jpg", desc: "A genetically inferior man assumes a superior identity to pursue his dream of space travel." },
    { title: "Children of Men", genre: "sci-fi", mood: "sad", duration: "long", poster: "assets/p/sf29.jpg", desc: "In a world where women are infertile, a man helps transport a miraculously pregnant woman." },
    { title: "The Road", genre: "sci-fi", mood: "sad", duration: "long", poster: "assets/p/sf30.jpg", desc: "A father defends his son in a dangerous post-apocalyptic world as they travel to the sea." },

    // ROMANCE
    { title: "Before Sunrise", genre: "romance", mood: "lighthearted", duration: "short", poster: "assets/p/r1.jpg", desc: "A young man and woman meet on a train in Europe and wind up spending one evening together in Vienna." },
    { title: "The Art of Getting By", genre: "romance", mood: "lighthearted", duration: "short", poster: "assets/p/r2.jpg", desc: "A lonely and fatalistic teen who has made it to his senior year without ever having done a day of work befriends a girl." },
    { title: "About Time", genre: "romance", mood: "lighthearted", duration: "medium", poster: "assets/p/r3.jpg", desc: "At the age of 21, Tim discovers he can travel in time and change what happens in his own life." },
    { title: "Crazy Rich Asians", genre: "romance", mood: "lighthearted", duration: "medium", poster: "assets/p/r4.jpg", desc: "A New Yorker accompanies her boyfriend to his best friend's wedding in Singapore and meets his family." },
    { title: "The Princess Bride", genre: "romance", mood: "lighthearted", duration: "long", poster: "assets/p/r5.jpg", desc: "While home sick in bed, a young boy's grandfather reads him the story of a farmboy-turned-pirate." },
    { title: "Jerry Maguire", genre: "romance", mood: "lighthearted", duration: "long", poster: "assets/p/r6.jpg", desc: "When a sports agent has a moral epiphany and is fired, he tests his new philosophy with only one loyal colleague." },

    { title: "The Lunchbox", genre: "romance", mood: "thought-provoking", duration: "short", poster: "assets/p/r7.jpg", desc: "A mistaken delivery in Mumbai's famously efficient lunchbox delivery system connects a young housewife to an older man." },
    { title: "Certified Copy", genre: "romance", mood: "thought-provoking", duration: "short", poster: "assets/p/r8.jpg", desc: "In Tuscany, a man and a woman's relationship is discussed and examined over the course of a day." },
    { title: "Her", genre: "romance", mood: "thought-provoking", duration: "medium", poster: "assets/p/r9.jpg", desc: "In a near future, a lonely writer develops an unlikely relationship with an operating system." },
    { title: "Eternal Sunshine", genre: "romance", mood: "thought-provoking", duration: "medium", poster: "assets/p/r10.jpg", desc: "A couple undergoes a medical procedure to have each other erased from their memories." },
    { title: "The Lobster", genre: "romance", mood: "thought-provoking", duration: "long", poster: "assets/p/r11.jpg", desc: "In a dystopian near future, single people are arrested and transferred to a hotel where they must find a partner." },
    { title: "Meet Joe Black", genre: "romance", mood: "thought-provoking", duration: "long", poster: "assets/p/r12.jpg", desc: "Death, who takes the form of a young man, asks a media tycoon to guide him and falls for his daughter." },

    { title: "Past Lives", genre: "romance", mood: "emotional", duration: "short", poster: "assets/p/r13.jpg", desc: "Two deeply connected childhood friends are wrest apart after one's family emigrates from South Korea." },
    { title: "Portrait of a Lady on Fire", genre: "romance", mood: "emotional", duration: "short", poster: "assets/p/r14.jpg", desc: "On an isolated island in Brittany at the end of the 18th century, a female artist is commissioned to paint a wedding portrait." },
    { title: "The Notebook", genre: "romance", mood: "emotional", duration: "medium", poster: "assets/p/r15.jpg", desc: "A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom." },
    { title: "A Star is Born", genre: "romance", mood: "emotional", duration: "medium", poster: "assets/p/r16.jpg", desc: "A musician helps a young singer find fame as age and alcoholism send his own career into a downward spiral." },
    { title: "Titanic", genre: "romance", mood: "emotional", duration: "long", poster: "assets/p/r17.jpg", desc: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic." },
    { title: "Les Misérables", genre: "romance", mood: "emotional", duration: "long", poster: "assets/p/r18.jpg", desc: "In 19th-century France, Jean Valjean is hunted for decades by the ruthless policeman Javert." },

    { title: "Palm Springs", genre: "romance", mood: "funny", duration: "short", poster: "assets/p/r19.jpg", desc: "Stuck in a time loop, two wedding guests develop a budding romance while living the same day over and over." },
    { title: "Forgetting Sarah Marshall", genre: "romance", mood: "funny", duration: "short", poster: "assets/p/r20.jpg", desc: "Devastated Peter takes a Hawaiian vacation in order to deal with a recent break-up with his TV star girlfriend." },
    { title: "The Proposal", genre: "romance", mood: "funny", duration: "medium", poster: "assets/p/r21.jpg", desc: "A pushy boss forces her young assistant to marry her in order to keep her visa status in the U.S." },
    { title: "How to Lose a Guy in 10 Days", genre: "romance", mood: "funny", duration: "medium", poster: "assets/p/r22.jpg", desc: "Benjamin Barry is an advertising executive and ladies' man who, to win a big campaign, bets that he can make a woman fall in love with him." },
    { title: "When Harry Met Sally", genre: "romance", mood: "funny", duration: "long", poster: "assets/p/r23.jpg", desc: "Harry and Sally have known each other for years, and are very good friends, but they fear sex would ruin the friendship." },
    { title: "Crazy, Stupid, Love.", genre: "romance", mood: "funny", duration: "long", poster: "assets/p/r24.jpg", desc: "A middle-aged husband's life changes dramatically when his wife asks him for a divorce. He seeks to rediscover his manhood." },

    { title: "Ghost", genre: "romance", mood: "sad", duration: "short", poster: "assets/p/r25.jpg", desc: "After a young man is murdered, his spirit stays behind to warn his lover of impending danger." },
    { title: "Brief Encounter", genre: "romance", mood: "sad", duration: "short", poster: "assets/p/r26.jpg", desc: "Meeting a stranger in a railway station, a woman is tempted to cheat on her husband." },
    { title: "Blue Valentine", genre: "romance", mood: "sad", duration: "medium", poster: "assets/p/r27.jpg", desc: "The relationship of a contemporary married couple, charting their evolution over a span of years." },
    { title: "Brokeback Mountain", genre: "romance", mood: "sad", duration: "medium", poster: "assets/p/r28.jpg", desc: "The story of a forbidden and secretive relationship between two cowboys, and their lives over the years." },
    { title: "A Walk to Remember", genre: "romance", mood: "sad", duration: "long", poster: "assets/p/r29.jpg", desc: "The story of two North Carolina teens, Landon Carter and Jamie Sullivan, who are thrown together after Landon gets into trouble." },
    { title: "Me Before You", genre: "romance", mood: "sad", duration: "long", poster: "assets/p/r30.jpg", desc: "A girl in a small town forms an unlikely bond with a recently-paralyzed man she's taking care of." },

    // ANIMATION
    { title: "Despicable Me", genre: "animation", mood: "lighthearted", duration: "short", poster: "assets/p/an1.jpg", desc: "A criminal mastermind uses a trio of orphan girls as pawns for a grand scheme." },
    { title: "The Secret Life of Pets", genre: "animation", mood: "lighthearted", duration: "short", poster: "assets/p/an2.jpg", desc: "The quiet life of a terrier named Max is upended when his owner takes in a stray." },
    { title: "Shrek", genre: "animation", mood: "lighthearted", duration: "medium", poster: "assets/p/an3.jpg", desc: "An ogre finds his swamp invaded by fairy tale creatures and must rescue a princess." },
    { title: "Zootopia", genre: "animation", mood: "lighthearted", duration: "medium", poster: "assets/p/an4.jpg", desc: "In a city of anthropomorphic animals, a rookie bunny cop and a cynical con artist fox must work together." },
    { title: "Klaus", genre: "animation", mood: "lighthearted", duration: "long", poster: "assets/p/an5.jpg", desc: "A simple act of kindness always sparks another, even in a frozen, faraway place." },
    { title: "Ratatouille", genre: "animation", mood: "lighthearted", duration: "long", poster: "assets/p/an6.jpg", desc: "A rat who can cook makes an unusual alliance with a young kitchen worker at a famous restaurant." },

    { title: "Ghost in the Shell", genre: "animation", mood: "thought-provoking", duration: "short", poster: "assets/p/an7.jpg", desc: "A cyborg policewoman and her partner hunt a mysterious and powerful hacker called the Puppet Master." },
    { title: "Paprika", genre: "animation", mood: "thought-provoking", duration: "short", poster: "assets/p/an8.jpg", desc: "When a machine that allows therapists to enter their patients' dreams is stolen, all hell breaks loose." },
    { title: "Inside Out", genre: "animation", mood: "thought-provoking", duration: "medium", poster: "assets/p/an9.jpg", desc: "After a young girl is uprooted from her Midwest life, her emotions conflict on how best to navigate a new city." },
    { title: "Spirited Away", genre: "animation", mood: "thought-provoking", duration: "medium", poster: "assets/p/an10.jpg", desc: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods and spirits." },
    { title: "Spider-Man: Across the Spider-Verse", genre: "animation", mood: "thought-provoking", duration: "long", poster: "assets/p/an11.jpg", desc: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its existence." },
    { title: "Princess Mononoke", genre: "animation", mood: "thought-provoking", duration: "long", poster: "assets/p/an12.jpg", desc: "On a journey to find a cure for a Tatarigami's curse, Ashitaka finds himself in the middle of a war between forest gods and humans." },

    { title: "Up", genre: "animation", mood: "emotional", duration: "short", poster: "assets/p/an13.jpg", desc: "78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons." },
    { title: "The Iron Giant", genre: "animation", mood: "emotional", duration: "short", poster: "assets/p/an14.jpg", desc: "A young boy befriends a giant robot from outer space that a paranoid government agent wants to destroy." },
    { title: "Coco", genre: "animation", mood: "emotional", duration: "medium", poster: "assets/p/an15.jpg", desc: "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead." },
    { title: "How to Train Your Dragon", genre: "animation", mood: "emotional", duration: "medium", poster: "assets/p/an16.jpg", desc: "A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself." },
    { title: "The Lion King", genre: "animation", mood: "emotional", duration: "long", poster: "assets/p/an17.jpg", desc: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself." },
    { title: "Your Name", genre: "animation", mood: "emotional", duration: "long", poster: "assets/p/an18.jpg", desc: "Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?" },

    { title: "The LEGO Movie", genre: "animation", mood: "funny", duration: "short", poster: "assets/p/an19.jpg", desc: "An ordinary LEGO construction worker, thought to be the prophesied 'Special', is recruited to join a quest." },
    { title: "Minions", genre: "animation", mood: "funny", duration: "short", poster: "assets/p/an20.jpg", desc: "Minions Stuart, Kevin, and Bob are recruited by Scarlet Overkill, a supervillain who hatches a plot to take over the world." },
    { title: "Kung Fu Panda", genre: "animation", mood: "funny", duration: "medium", poster: "assets/p/an21.jpg", desc: "To everyone's surprise, including his own, Po, an overweight panda, is chosen as savior of the Valley of Peace." },
    { title: "Cloudy with a Chance of Meatballs", genre: "animation", mood: "funny", duration: "medium", poster: "assets/p/an22.jpg", desc: "A local scientist is often regarded as a failure until he invents a machine that can make food fall from the sky." },
    { title: "Toy Story 3", genre: "animation", mood: "funny", duration: "long", poster: "assets/p/an23.jpg", desc: "The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college." },
    { title: "Monsters, Inc.", genre: "animation", mood: "funny", duration: "long", poster: "assets/p/an24.jpg", desc: "In order to power the city, monsters have to scare children so that they scream." },

    { title: "Grave of the Fireflies", genre: "animation", mood: "sad", duration: "short", poster: "assets/p/an25.jpg", desc: "A young boy and his little sister struggle to survive in Japan during World War II." },
    { title: "The Land Before Time", genre: "animation", mood: "sad", duration: "short", poster: "assets/p/an26.jpg", desc: "An orphaned brontosaurus teams up with other young dinosaurs in order to reunite with their families." },
    { title: "The Fox and the Hound", genre: "animation", mood: "sad", duration: "medium", poster: "assets/p/an27.jpg", desc: "Two childhood friends are forced to become enemies by society's expectations." },
    { title: "Anomalisa", genre: "animation", mood: "sad", duration: "medium", poster: "assets/p/an28.jpg", desc: "A man crippled by the mundanity of his life experiences something out of the ordinary." },
    { title: "Watership Down", genre: "animation", mood: "sad", duration: "long", poster: "assets/p/an29.jpg", desc: "A group of rabbits flee their doomed warren and face many dangers to find a new home." },
    { title: "The Tale of The Princess Kaguya", genre: "animation", mood: "sad", duration: "long", poster: "assets/p/an30.jpg", desc: "Found inside a shining stalk of bamboo by an old bamboo cutter and his wife, a tiny girl grows rapidly."}

];


export default movieDatabase;